import type { Category, Product } from "./types";

type CategorySeed = Omit<Category, "image">;

const categorySeeds: CategorySeed[] = [
  {
    slug: "vegetables",
    name: "Vegetables",
    tagline: "Mandi-fresh, sorted and graded",
    gradient: "from-emerald-100 to-lime-50",
    subcategories: ["Daily Staples", "Leafy", "Gourds", "Salad"],
  },
  {
    slug: "fruits",
    name: "Fruits",
    tagline: "Seasonal picks from source farms",
    gradient: "from-amber-100 to-orange-50",
    subcategories: ["Seasonal", "Citrus", "Imported"],
  },
  {
    slug: "exotics-herbs",
    name: "Exotics & Herbs",
    tagline: "Continental menu essentials",
    gradient: "from-teal-100 to-emerald-50",
    subcategories: ["Herbs", "Exotic Veg", "Microgreens"],
  },
  {
    slug: "chicken-poultry",
    name: "Chicken & Poultry",
    tagline: "Cut to your spec, cold-chain delivered",
    gradient: "from-rose-100 to-orange-50",
    subcategories: ["Curry Cuts", "Boneless", "Speciality", "Eggs"],
  },
  {
    slug: "mutton-meat",
    name: "Mutton & Meat",
    tagline: "Halal certified, hand-selected",
    gradient: "from-red-100 to-rose-50",
    subcategories: ["Mutton", "Lamb", "Cold Cuts"],
  },
  {
    slug: "seafood",
    name: "Seafood",
    tagline: "Harbour to kitchen within 24 hours",
    gradient: "from-sky-100 to-cyan-50",
    subcategories: ["Fish", "Prawns", "Shellfish"],
  },
  {
    slug: "dairy",
    name: "Dairy & Eggs",
    tagline: "Cold-chain milk, paneer and cheese",
    gradient: "from-yellow-100 to-amber-50",
    subcategories: ["Milk", "Paneer & Cheese", "Curd & Cream"],
  },
  {
    slug: "masalas-spices",
    name: "Masalas & Spices",
    tagline: "Bulk packs at wholesale rates",
    gradient: "from-orange-100 to-red-50",
    subcategories: ["Whole Spices", "Ground Masala", "Blends"],
  },
  {
    slug: "grains-pulses",
    name: "Rice, Atta & Pulses",
    tagline: "Mill-direct sacks, no middlemen",
    gradient: "from-stone-100 to-amber-50",
    subcategories: ["Rice", "Flour", "Pulses"],
  },
  {
    slug: "oils-ghee",
    name: "Oils & Ghee",
    tagline: "Refined, filtered and cold-pressed",
    gradient: "from-lime-100 to-yellow-50",
    subcategories: ["Cooking Oil", "Ghee & Butter"],
  },
  {
    slug: "packaging",
    name: "Packaging & Disposables",
    tagline: "Leak-proof delivery packaging",
    gradient: "from-indigo-100 to-sky-50",
    subcategories: ["Containers", "Bags & Covers", "Cutlery"],
  },
  {
    slug: "cleaning",
    name: "Kitchen & Cleaning",
    tagline: "FSSAI-compliant hygiene supplies",
    gradient: "from-violet-100 to-indigo-50",
    subcategories: ["Cleaning", "Hygiene", "Kitchen Tools"],
  },
];

export const categories: Category[] = categorySeeds.map((seed) => ({
  ...seed,
  image: `/categories/${seed.slug}.jpg`,
}));

export const categoryBySlug = (slug: string) =>
  categories.find((category) => category.slug === slug);

/** Catalogue entries as authored; the image path is derived from the id below. */
type ProductSeed = Omit<Product, "image">;

const p = (product: ProductSeed): ProductSeed => product;

const seeds: ProductSeed[] = [
  // ---------------------------------------------------------------- Vegetables
  p({
    id: "onion-nashik",
    name: "Onion Nashik",
    localName: "Pyaaz",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "Sorted, 5 kg net bag",
    unit: "kg",
    price: 28,
    mrp: 38,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Nashik, Maharashtra",
    shelfLife: "12-15 days",
    storage: "Dry, ventilated store room",
    description:
      "Medium-sized Nashik onions, machine-sorted for uniform 50-60 mm diameter so your gravy prep stays consistent batch to batch.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [
      { qty: 25, price: 26 },
      { qty: 50, price: 24 },
    ],
  }),
  p({
    id: "tomato-hybrid",
    name: "Tomato Hybrid",
    localName: "Tamatar",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "Crate, 10 kg",
    unit: "kg",
    price: 32,
    mrp: 45,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Kolar, Karnataka",
    shelfLife: "5-6 days",
    storage: "8-12°C, away from direct sun",
    description:
      "Firm hybrid tomatoes with high pulp yield, graded for gravy and puree use. Delivered in ventilated crates to cut transit damage.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 25, price: 29 }],
  }),
  p({
    id: "potato-jyoti",
    name: "Potato Jyoti",
    localName: "Aloo",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "Sorted, 10 kg bag",
    unit: "kg",
    price: 24,
    mrp: 32,
    gstRate: 0,
    moq: 10,
    step: 5,
    origin: "Agra, Uttar Pradesh",
    shelfLife: "20-25 days",
    storage: "Cool dark store, 10-15°C",
    description:
      "High-starch Jyoti variety that holds shape after frying. Ideal for fries, samosa filling and dum aloo.",
    tags: [],
    inStock: true,
    bulkSlabs: [{ qty: 50, price: 21 }],
  }),
  p({
    id: "ginger",
    name: "Ginger",
    localName: "Adrak",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "1 kg pack",
    unit: "kg",
    price: 96,
    mrp: 130,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Wayanad, Kerala",
    shelfLife: "10-12 days",
    storage: "Cool and dry",
    description:
      "Thick-rhizome ginger with low fibre, cleaned of soil so you lose less in peeling.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "garlic",
    name: "Garlic",
    localName: "Lehsun",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "1 kg net bag",
    unit: "kg",
    price: 145,
    mrp: 185,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Madhya Pradesh",
    shelfLife: "3-4 weeks",
    storage: "Cool, dry, ventilated",
    description:
      "Medium-sized white bulbs with tight cloves and low moisture. Sorted to remove sprouted or damaged heads.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "garlic-peeled",
    name: "Garlic Peeled",
    localName: "Lehsun",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "1 kg vacuum pack",
    unit: "kg",
    price: 210,
    mrp: 260,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Madhya Pradesh",
    shelfLife: "7 days (chilled)",
    storage: "0-4°C refrigerated",
    description:
      "Hand-peeled garlic cloves, vacuum packed the same day. Saves roughly 45 minutes of prep labour per kilo.",
    tags: ["Saves prep time"],
    inStock: true,
  }),
  p({
    id: "green-chilli",
    name: "Green Chilli",
    localName: "Hari Mirch",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "1 kg pack",
    unit: "kg",
    price: 54,
    mrp: 72,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Guntur, Andhra Pradesh",
    shelfLife: "6-7 days",
    storage: "Refrigerated 8-10°C",
    description: "Medium-hot long green chillies, stalk intact for longer shelf life.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "coriander-leaves",
    name: "Coriander Leaves",
    localName: "Dhaniya Patta",
    category: "vegetables",
    subcategory: "Leafy",
    packSize: "Bundle, 500 g",
    unit: "bundle",
    price: 22,
    mrp: 30,
    gstRate: 0,
    moq: 4,
    step: 2,
    origin: "Local farms",
    shelfLife: "3-4 days",
    storage: "Refrigerated, stems in water",
    description: "Fresh-cut coriander with tender stems, washed and bundled the night before dispatch.",
    tags: ["Daily fresh"],
    inStock: true,
  }),
  p({
    id: "palak",
    name: "Spinach",
    localName: "Palak",
    category: "vegetables",
    subcategory: "Leafy",
    packSize: "Bundle, 1 kg",
    unit: "bundle",
    price: 34,
    mrp: 45,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Local farms",
    shelfLife: "3-4 days",
    storage: "Refrigerated 4-8°C",
    description: "Broad-leaf palak, de-rooted and rinsed, ready for blanching.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "capsicum-green",
    name: "Capsicum Green",
    localName: "Shimla Mirch",
    category: "vegetables",
    subcategory: "Salad",
    packSize: "1 kg pack",
    unit: "kg",
    price: 48,
    mrp: 66,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Hosur, Tamil Nadu",
    shelfLife: "7-8 days",
    storage: "Refrigerated 8-10°C",
    description: "Thick-walled capsicum with a firm bite, sized 80-100 g each for even dicing.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "cauliflower",
    name: "Cauliflower",
    localName: "Phool Gobhi",
    category: "vegetables",
    subcategory: "Daily Staples",
    packSize: "Trimmed, 5 kg",
    unit: "kg",
    price: 38,
    mrp: 50,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Ooty, Tamil Nadu",
    shelfLife: "5-6 days",
    storage: "Refrigerated 4-8°C",
    description: "Tight white curds, leaves trimmed so you pay for usable weight only.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "bottle-gourd",
    name: "Bottle Gourd",
    localName: "Lauki",
    category: "vegetables",
    subcategory: "Gourds",
    packSize: "5 kg pack",
    unit: "kg",
    price: 26,
    mrp: 34,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Local farms",
    shelfLife: "7-8 days",
    storage: "Cool and dry",
    description: "Tender young lauki with soft seeds, picked at 700-900 g each.",
    tags: [],
    inStock: false,
  }),
  p({
    id: "cucumber",
    name: "Cucumber English",
    localName: "Kheera",
    category: "vegetables",
    subcategory: "Salad",
    packSize: "5 kg pack",
    unit: "kg",
    price: 36,
    mrp: 48,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Pune, Maharashtra",
    shelfLife: "6-7 days",
    storage: "Refrigerated 10-12°C",
    description: "Seedless salad cucumber with a thin skin, no peeling needed.",
    tags: [],
    inStock: true,
  }),

  // -------------------------------------------------------------------- Fruits
  p({
    id: "lemon",
    name: "Lemon",
    localName: "Nimbu",
    category: "fruits",
    subcategory: "Citrus",
    packSize: "1 kg pack",
    unit: "kg",
    price: 62,
    mrp: 90,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Vijayawada, Andhra Pradesh",
    shelfLife: "10-12 days",
    storage: "Cool and dry",
    description: "Thin-skinned juicy lemons averaging 40 ml juice per fruit.",
    tags: ["Bestseller"],
    inStock: true,
  }),
  p({
    id: "banana-robusta",
    name: "Banana Robusta",
    localName: "Kela",
    category: "fruits",
    subcategory: "Seasonal",
    packSize: "Crate, 12 kg",
    unit: "kg",
    price: 40,
    mrp: 55,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Theni, Tamil Nadu",
    shelfLife: "4-5 days",
    storage: "Room temperature, do not refrigerate",
    description: "Ripening-controlled robusta bananas delivered at stage 4 so they hold two more days on your counter.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "pineapple",
    name: "Pineapple Queen",
    category: "fruits",
    subcategory: "Seasonal",
    packSize: "Piece, 1-1.2 kg",
    unit: "pc",
    price: 58,
    mrp: 75,
    gstRate: 0,
    moq: 4,
    step: 2,
    origin: "Kerala",
    shelfLife: "6-7 days",
    storage: "Cool and dry",
    description: "High-brix queen pineapple, sweet enough for juices without added sugar.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "pomegranate",
    name: "Pomegranate Bhagwa",
    localName: "Anar",
    category: "fruits",
    subcategory: "Seasonal",
    packSize: "3 kg box",
    unit: "kg",
    price: 145,
    mrp: 190,
    gstRate: 0,
    moq: 3,
    step: 3,
    origin: "Solapur, Maharashtra",
    shelfLife: "12-15 days",
    storage: "Refrigerated 5-8°C",
    description: "Deep red Bhagwa arils with soft seeds, graded 250 g+ per fruit.",
    tags: ["Premium"],
    inStock: true,
  }),
  p({
    id: "apple-shimla",
    name: "Apple Shimla",
    localName: "Seb",
    category: "fruits",
    subcategory: "Seasonal",
    packSize: "5 kg box",
    unit: "kg",
    price: 168,
    mrp: 220,
    gstRate: 0,
    moq: 5,
    step: 5,
    origin: "Himachal Pradesh",
    shelfLife: "20-25 days",
    storage: "Refrigerated 2-4°C",
    description: "Cold-store Shimla apples, 100-125 count, crisp for salads and desserts.",
    tags: [],
    inStock: true,
  }),

  // ----------------------------------------------------------- Exotics & Herbs
  p({
    id: "broccoli",
    name: "Broccoli",
    category: "exotics-herbs",
    subcategory: "Exotic Veg",
    packSize: "1 kg pack",
    unit: "kg",
    price: 128,
    mrp: 170,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Ooty, Tamil Nadu",
    shelfLife: "5-6 days",
    storage: "Refrigerated 2-4°C",
    description: "Tight dark-green crowns, 300-400 g each, minimal stalk wastage.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "zucchini",
    name: "Zucchini Green",
    category: "exotics-herbs",
    subcategory: "Exotic Veg",
    packSize: "1 kg pack",
    unit: "kg",
    price: 96,
    mrp: 130,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Bengaluru rural",
    shelfLife: "6-7 days",
    storage: "Refrigerated 8-10°C",
    description: "Straight, uniform zucchini sized for clean discs and ribbons.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "iceberg-lettuce",
    name: "Iceberg Lettuce",
    category: "exotics-herbs",
    subcategory: "Exotic Veg",
    packSize: "Piece, 500-700 g",
    unit: "pc",
    price: 84,
    mrp: 110,
    gstRate: 0,
    moq: 4,
    step: 2,
    origin: "Ooty, Tamil Nadu",
    shelfLife: "5-6 days",
    storage: "Refrigerated 2-4°C",
    description: "Crunchy hydro-cooled iceberg heads that stay crisp through a full service.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "basil",
    name: "Italian Basil",
    category: "exotics-herbs",
    subcategory: "Herbs",
    packSize: "100 g clamshell",
    unit: "pack",
    price: 68,
    mrp: 90,
    gstRate: 5,
    moq: 2,
    step: 1,
    origin: "Hydroponic farms, Pune",
    shelfLife: "4-5 days",
    storage: "Refrigerated 8-10°C",
    description: "Large-leaf genovese basil grown hydroponically, no grit to wash out.",
    tags: ["Chef favourite"],
    inStock: true,
  }),
  p({
    id: "rosemary",
    name: "Rosemary",
    category: "exotics-herbs",
    subcategory: "Herbs",
    packSize: "50 g clamshell",
    unit: "pack",
    price: 74,
    mrp: 95,
    gstRate: 5,
    moq: 2,
    step: 1,
    origin: "Nilgiris",
    shelfLife: "7-8 days",
    storage: "Refrigerated 4-8°C",
    description: "Woody rosemary sprigs with a strong aroma, cut to 12 cm.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "mushroom-button",
    name: "Button Mushroom",
    category: "exotics-herbs",
    subcategory: "Exotic Veg",
    packSize: "200 g punnet",
    unit: "pack",
    price: 42,
    mrp: 60,
    gstRate: 5,
    moq: 10,
    step: 5,
    origin: "Pune, Maharashtra",
    shelfLife: "4-5 days",
    storage: "Refrigerated 2-4°C",
    description: "Closed-cap white button mushrooms, graded and punnet-packed for portion control.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 25, price: 39 }],
  }),

  // -------------------------------------------------------- Chicken & Poultry
  p({
    id: "chicken-curry-cut",
    name: "Chicken Curry Cut",
    localName: "Skinless, with bone",
    category: "chicken-poultry",
    subcategory: "Curry Cuts",
    packSize: "1 kg vacuum pack",
    unit: "kg",
    price: 178,
    mrp: 230,
    gstRate: 0,
    moq: 5,
    step: 1,
    origin: "Karnataka processing unit",
    shelfLife: "3 days chilled / 3 months frozen",
    storage: "0-4°C chilled",
    description:
      "Skinless curry cut in 12-14 uniform pieces from 1.2 kg birds. Antibiotic-residue tested, cut the same morning.",
    tags: ["Bestseller", "Cold chain"],
    inStock: true,
    bulkSlabs: [
      { qty: 20, price: 172 },
      { qty: 50, price: 165 },
    ],
  }),
  p({
    id: "chicken-boneless",
    name: "Chicken Boneless Breast",
    category: "chicken-poultry",
    subcategory: "Boneless",
    packSize: "1 kg vacuum pack",
    unit: "kg",
    price: 268,
    mrp: 340,
    gstRate: 0,
    moq: 3,
    step: 1,
    origin: "Karnataka processing unit",
    shelfLife: "3 days chilled",
    storage: "0-4°C chilled",
    description:
      "Trimmed breast fillets with tenderloin removed, 180-220 g each. Ideal for tikka, grills and continental mains.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 20, price: 258 }],
  }),
  p({
    id: "chicken-lollipop",
    name: "Chicken Lollipop",
    category: "chicken-poultry",
    subcategory: "Speciality",
    packSize: "1 kg pack (approx 22 pcs)",
    unit: "kg",
    price: 232,
    mrp: 290,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Karnataka processing unit",
    shelfLife: "3 days chilled",
    storage: "0-4°C chilled",
    description: "Frenched wing drumettes cleaned and shaped, ready for batter and fry.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "chicken-mince",
    name: "Chicken Mince",
    localName: "Keema",
    category: "chicken-poultry",
    subcategory: "Boneless",
    packSize: "1 kg pack",
    unit: "kg",
    price: 246,
    mrp: 310,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Karnataka processing unit",
    shelfLife: "2 days chilled",
    storage: "0-4°C chilled",
    description: "Coarse 6 mm mince from leg meat, 12% fat, for kebabs and keema gravies.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "eggs-tray",
    name: "Table Eggs",
    category: "chicken-poultry",
    subcategory: "Eggs",
    packSize: "Tray of 30",
    unit: "tray",
    price: 186,
    mrp: 225,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Namakkal, Tamil Nadu",
    shelfLife: "12-15 days",
    storage: "Cool and dry, 15-18°C",
    description: "Grade A brown eggs, 55-60 g each, candled for cracks before packing.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 10, price: 178 }],
  }),

  // ------------------------------------------------------------- Mutton & Meat
  p({
    id: "mutton-curry-cut",
    name: "Mutton Curry Cut",
    localName: "Goat, bone-in",
    category: "mutton-meat",
    subcategory: "Mutton",
    packSize: "1 kg vacuum pack",
    unit: "kg",
    price: 748,
    mrp: 880,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Rajasthan & Karnataka farms",
    shelfLife: "3 days chilled",
    storage: "0-4°C chilled",
    description:
      "Halal-certified goat curry cut from animals under 12 months, mixed shoulder and leg pieces at 40 g each.",
    tags: ["Halal", "Cold chain"],
    inStock: true,
    bulkSlabs: [{ qty: 10, price: 725 }],
  }),
  p({
    id: "mutton-keema",
    name: "Mutton Keema",
    category: "mutton-meat",
    subcategory: "Mutton",
    packSize: "1 kg pack",
    unit: "kg",
    price: 812,
    mrp: 940,
    gstRate: 0,
    moq: 1,
    step: 1,
    origin: "Rajasthan farms",
    shelfLife: "2 days chilled",
    storage: "0-4°C chilled",
    description: "Fine 4 mm goat mince from lean shoulder, ideal for seekh and kheema pav.",
    tags: ["Halal"],
    inStock: true,
  }),
  p({
    id: "lamb-chops",
    name: "Lamb Rib Chops",
    category: "mutton-meat",
    subcategory: "Lamb",
    packSize: "1 kg pack (approx 8 pcs)",
    unit: "kg",
    price: 1180,
    mrp: 1380,
    gstRate: 0,
    moq: 1,
    step: 1,
    origin: "New Zealand",
    shelfLife: "6 months frozen",
    storage: "-18°C frozen",
    description: "Frenched rib chops cut at 120-130 g, vacuum sealed and blast frozen.",
    tags: ["Premium", "Imported"],
    inStock: true,
  }),
  p({
    id: "chicken-salami",
    name: "Chicken Salami",
    category: "mutton-meat",
    subcategory: "Cold Cuts",
    packSize: "500 g pack",
    unit: "pack",
    price: 235,
    mrp: 290,
    gstRate: 12,
    moq: 2,
    step: 1,
    origin: "Hyderabad",
    shelfLife: "45 days",
    storage: "0-4°C chilled",
    description: "Pre-sliced chicken salami, roughly 25 slices per pack, for sandwiches and pizzas.",
    tags: [],
    inStock: true,
  }),

  // ------------------------------------------------------------------ Seafood
  p({
    id: "prawns-medium",
    name: "Prawns Medium (26/30)",
    localName: "Jhinga",
    category: "seafood",
    subcategory: "Prawns",
    packSize: "1 kg pack, deveined",
    unit: "kg",
    price: 545,
    mrp: 690,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Nellore, Andhra Pradesh",
    shelfLife: "2 days chilled / 6 months frozen",
    storage: "0-4°C chilled",
    description: "Peeled and deveined vannamei prawns, tail-off, 26-30 count per pound.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 10, price: 528 }],
  }),
  p({
    id: "seer-fish",
    name: "Seer Fish Steaks",
    localName: "Surmai",
    category: "seafood",
    subcategory: "Fish",
    packSize: "1 kg pack",
    unit: "kg",
    price: 890,
    mrp: 1050,
    gstRate: 0,
    moq: 1,
    step: 1,
    origin: "Mangaluru harbour",
    shelfLife: "2 days chilled",
    storage: "0-2°C on ice",
    description: "Centre-cut surmai steaks at 150 g each, from fish landed within 24 hours.",
    tags: ["Premium"],
    inStock: true,
  }),
  p({
    id: "basa-fillet",
    name: "Basa Fillet",
    category: "seafood",
    subcategory: "Fish",
    packSize: "1 kg pack, frozen",
    unit: "kg",
    price: 318,
    mrp: 420,
    gstRate: 0,
    moq: 2,
    step: 1,
    origin: "Vietnam",
    shelfLife: "12 months frozen",
    storage: "-18°C frozen",
    description: "Boneless, skinless basa fillets at 200-220 g, IQF with a low glaze percentage.",
    tags: ["Imported"],
    inStock: true,
  }),
  p({
    id: "pomfret",
    name: "Silver Pomfret",
    localName: "Paplet",
    category: "seafood",
    subcategory: "Fish",
    packSize: "1 kg (2-3 pcs), cleaned",
    unit: "kg",
    price: 1150,
    mrp: 1350,
    gstRate: 0,
    moq: 1,
    step: 1,
    origin: "Mumbai harbour",
    shelfLife: "2 days chilled",
    storage: "0-2°C on ice",
    description: "Whole silver pomfret, gutted and scaled, 300-400 g each.",
    tags: ["Premium"],
    inStock: false,
  }),

  // -------------------------------------------------------------------- Dairy
  p({
    id: "paneer",
    name: "Fresh Paneer Block",
    category: "dairy",
    subcategory: "Paneer & Cheese",
    packSize: "1 kg block",
    unit: "kg",
    price: 322,
    mrp: 400,
    gstRate: 5,
    moq: 2,
    step: 1,
    origin: "Hosur dairy",
    shelfLife: "6 days",
    storage: "0-4°C chilled",
    description: "Cow-milk paneer set overnight, 22% fat, holds shape in gravies without crumbling.",
    tags: ["Bestseller", "Cold chain"],
    inStock: true,
    bulkSlabs: [{ qty: 10, price: 312 }],
  }),
  p({
    id: "mozzarella",
    name: "Mozzarella Cheese Block",
    category: "dairy",
    subcategory: "Paneer & Cheese",
    packSize: "2 kg block",
    unit: "pack",
    price: 780,
    mrp: 950,
    gstRate: 12,
    moq: 1,
    step: 1,
    origin: "Punjab dairy",
    shelfLife: "3 months",
    storage: "0-4°C chilled",
    description: "Low-moisture mozzarella with a controlled melt and stretch, built for pizza ovens.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "toned-milk",
    name: "Toned Milk",
    category: "dairy",
    subcategory: "Milk",
    packSize: "Crate, 12 x 1 ltr",
    unit: "crate",
    price: 636,
    mrp: 720,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Hosur dairy",
    shelfLife: "2 days",
    storage: "0-4°C chilled",
    description: "3% fat toned milk in 1 litre pouches, delivered in the morning cold-chain run.",
    tags: ["Daily fresh"],
    inStock: true,
  }),
  p({
    id: "curd-bucket",
    name: "Set Curd Bucket",
    localName: "Dahi",
    category: "dairy",
    subcategory: "Curd & Cream",
    packSize: "5 kg bucket",
    unit: "bucket",
    price: 355,
    mrp: 430,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Hosur dairy",
    shelfLife: "5 days",
    storage: "0-4°C chilled",
    description: "Thick set curd with 0.7% acidity, consistent for raita, marinades and lassi.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "amul-butter",
    name: "Table Butter Salted",
    category: "dairy",
    subcategory: "Curd & Cream",
    packSize: "500 g pack",
    unit: "pack",
    price: 265,
    mrp: 295,
    gstRate: 12,
    moq: 4,
    step: 2,
    origin: "Gujarat",
    shelfLife: "4 months",
    storage: "0-4°C chilled",
    description: "Salted table butter, 80% milk fat, for tadka, naan brushing and bakery use.",
    tags: [],
    inStock: true,
  }),

  // ---------------------------------------------------------- Masalas & Spices
  p({
    id: "kashmiri-chilli-powder",
    name: "Kashmiri Chilli Powder",
    category: "masalas-spices",
    subcategory: "Ground Masala",
    packSize: "5 kg pack",
    unit: "pack",
    price: 1780,
    mrp: 2150,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Byadgi, Karnataka",
    shelfLife: "9 months",
    storage: "Airtight, away from moisture",
    description: "Byadgi chilli ground for colour rather than heat, ASTA 80+, no added colourants.",
    tags: ["Bestseller"],
    inStock: true,
  }),
  p({
    id: "turmeric-powder",
    name: "Turmeric Powder",
    localName: "Haldi",
    category: "masalas-spices",
    subcategory: "Ground Masala",
    packSize: "5 kg pack",
    unit: "pack",
    price: 1140,
    mrp: 1400,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Erode, Tamil Nadu",
    shelfLife: "12 months",
    storage: "Airtight, cool and dry",
    description: "Erode turmeric with 3.5% curcumin, lab tested for lead chromate adulteration.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "garam-masala",
    name: "Garam Masala Blend",
    category: "masalas-spices",
    subcategory: "Blends",
    packSize: "1 kg pack",
    unit: "pack",
    price: 620,
    mrp: 780,
    gstRate: 5,
    moq: 2,
    step: 1,
    origin: "Blended in Kochi",
    shelfLife: "9 months",
    storage: "Airtight, cool and dry",
    description: "House blend of 13 spices, roasted and stone-ground in small batches every fortnight.",
    tags: ["Chef favourite"],
    inStock: true,
  }),
  p({
    id: "cumin-seeds",
    name: "Cumin Seeds",
    localName: "Jeera",
    category: "masalas-spices",
    subcategory: "Whole Spices",
    packSize: "5 kg pack",
    unit: "pack",
    price: 1650,
    mrp: 1980,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Unjha, Gujarat",
    shelfLife: "12 months",
    storage: "Airtight, cool and dry",
    description: "Machine-cleaned singapore cumin, 99% purity, high volatile oil content.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "cardamom",
    name: "Green Cardamom",
    localName: "Elaichi",
    category: "masalas-spices",
    subcategory: "Whole Spices",
    packSize: "500 g pack",
    unit: "pack",
    price: 1420,
    mrp: 1700,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Idukki, Kerala",
    shelfLife: "12 months",
    storage: "Airtight, cool and dry",
    description: "7 mm bold green cardamom, hand-sorted, deep green with an intense aroma.",
    tags: ["Premium"],
    inStock: true,
  }),

  // ------------------------------------------------------------ Grains, Pulses
  p({
    id: "basmati-rice",
    name: "Basmati Rice Long Grain",
    category: "grains-pulses",
    subcategory: "Rice",
    packSize: "26 kg bag",
    unit: "bag",
    price: 2340,
    mrp: 2750,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Karnal, Haryana",
    shelfLife: "18 months",
    storage: "Dry store on pallets",
    description: "Two-year aged basmati averaging 8.2 mm grain length, elongates well for biryani.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 5, price: 2280 }],
  }),
  p({
    id: "sona-masoori",
    name: "Sona Masoori Rice",
    category: "grains-pulses",
    subcategory: "Rice",
    packSize: "25 kg bag",
    unit: "bag",
    price: 1420,
    mrp: 1680,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Raichur, Karnataka",
    shelfLife: "12 months",
    storage: "Dry store on pallets",
    description: "One-year old sona masoori, low starch, the daily-meal workhorse for South Indian kitchens.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "chakki-atta",
    name: "Chakki Fresh Atta",
    category: "grains-pulses",
    subcategory: "Flour",
    packSize: "50 kg bag",
    unit: "bag",
    price: 1780,
    mrp: 2050,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Madhya Pradesh mill",
    shelfLife: "4 months",
    storage: "Dry store on pallets",
    description: "Stone-ground whole wheat atta with bran retained, high water absorption for soft rotis.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "toor-dal",
    name: "Toor Dal",
    localName: "Arhar",
    category: "grains-pulses",
    subcategory: "Pulses",
    packSize: "30 kg bag",
    unit: "bag",
    price: 4350,
    mrp: 4900,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Kalaburagi, Karnataka",
    shelfLife: "9 months",
    storage: "Dry store on pallets",
    description: "Unpolished toor dal, double-cleaned, cooks to a consistent sambar body.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "maida",
    name: "Maida Refined Flour",
    category: "grains-pulses",
    subcategory: "Flour",
    packSize: "50 kg bag",
    unit: "bag",
    price: 1620,
    mrp: 1900,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Tamil Nadu mill",
    shelfLife: "6 months",
    storage: "Dry store on pallets",
    description: "Bakery-grade maida with 9-10% protein, suited to naan, breads and pastry.",
    tags: [],
    inStock: true,
  }),

  // ---------------------------------------------------------------- Oils, Ghee
  p({
    id: "sunflower-oil",
    name: "Refined Sunflower Oil",
    category: "oils-ghee",
    subcategory: "Cooking Oil",
    packSize: "15 ltr tin",
    unit: "tin",
    price: 1985,
    mrp: 2250,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Andhra Pradesh refinery",
    shelfLife: "9 months",
    storage: "Cool, dark store",
    description: "Refined sunflower oil with a 232°C smoke point, stable across repeated frying cycles.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 5, price: 1945 }],
  }),
  p({
    id: "groundnut-oil",
    name: "Filtered Groundnut Oil",
    category: "oils-ghee",
    subcategory: "Cooking Oil",
    packSize: "15 ltr tin",
    unit: "tin",
    price: 2480,
    mrp: 2800,
    gstRate: 5,
    moq: 1,
    step: 1,
    origin: "Gujarat",
    shelfLife: "9 months",
    storage: "Cool, dark store",
    description: "Wood-pressed and filtered groundnut oil that carries the aroma South Indian tiffin needs.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "cow-ghee",
    name: "Pure Cow Ghee",
    category: "oils-ghee",
    subcategory: "Ghee & Butter",
    packSize: "5 ltr tin",
    unit: "tin",
    price: 2740,
    mrp: 3150,
    gstRate: 12,
    moq: 1,
    step: 1,
    origin: "Punjab dairy",
    shelfLife: "9 months",
    storage: "Cool and dry",
    description: "Granular cow ghee made by the traditional bilona method, AGMARK certified.",
    tags: ["Premium"],
    inStock: true,
  }),

  // ------------------------------------------------------- Packaging, Cleaning
  p({
    id: "round-containers",
    name: "Round Food Containers 500 ml",
    category: "packaging",
    subcategory: "Containers",
    packSize: "Carton of 300 sets",
    unit: "carton",
    price: 1290,
    mrp: 1550,
    gstRate: 18,
    moq: 1,
    step: 1,
    origin: "Chennai",
    shelfLife: "-",
    storage: "Dry store",
    description: "Leak-proof polypropylene containers with lids, microwave safe and stackable for delivery.",
    tags: ["Bestseller"],
    inStock: true,
    bulkSlabs: [{ qty: 5, price: 1240 }],
  }),
  p({
    id: "paper-bags",
    name: "Kraft Paper Carry Bags",
    category: "packaging",
    subcategory: "Bags & Covers",
    packSize: "Bundle of 250",
    unit: "bundle",
    price: 640,
    mrp: 790,
    gstRate: 18,
    moq: 2,
    step: 1,
    origin: "Coimbatore",
    shelfLife: "-",
    storage: "Dry store",
    description: "120 GSM kraft bags with twisted handles, rated to 5 kg, printable on request.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "aluminium-foil",
    name: "Aluminium Foil Roll",
    category: "packaging",
    subcategory: "Containers",
    packSize: "9 micron, 1 kg roll",
    unit: "roll",
    price: 385,
    mrp: 460,
    gstRate: 18,
    moq: 2,
    step: 1,
    origin: "Maharashtra",
    shelfLife: "-",
    storage: "Dry store",
    description: "Food-grade foil roll for wrapping rolls, kebabs and hot holding.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "wooden-cutlery",
    name: "Wooden Cutlery Set",
    category: "packaging",
    subcategory: "Cutlery",
    packSize: "Box of 500 sets",
    unit: "box",
    price: 1120,
    mrp: 1400,
    gstRate: 18,
    moq: 1,
    step: 1,
    origin: "Kerala",
    shelfLife: "-",
    storage: "Dry store",
    description: "Birchwood spoon, fork and napkin in individually sealed sleeves. Plastic-ban compliant.",
    tags: ["Eco"],
    inStock: true,
  }),
  p({
    id: "dishwash-liquid",
    name: "Dishwash Liquid Concentrate",
    category: "cleaning",
    subcategory: "Cleaning",
    packSize: "5 ltr can",
    unit: "can",
    price: 465,
    mrp: 580,
    gstRate: 18,
    moq: 2,
    step: 1,
    origin: "Hyderabad",
    shelfLife: "24 months",
    storage: "Dry store",
    description: "Concentrated degreaser that dilutes 1:10, cuts through masala oils on steel.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "hand-gloves",
    name: "Nitrile Hand Gloves",
    category: "cleaning",
    subcategory: "Hygiene",
    packSize: "Box of 100",
    unit: "box",
    price: 395,
    mrp: 490,
    gstRate: 18,
    moq: 2,
    step: 1,
    origin: "Malaysia",
    shelfLife: "36 months",
    storage: "Dry store",
    description: "Powder-free food-handling gloves in medium and large, blue for easy detection.",
    tags: [],
    inStock: true,
  }),
  p({
    id: "floor-cleaner",
    name: "Kitchen Floor Cleaner",
    category: "cleaning",
    subcategory: "Cleaning",
    packSize: "5 ltr can",
    unit: "can",
    price: 410,
    mrp: 520,
    gstRate: 18,
    moq: 2,
    step: 1,
    origin: "Chennai",
    shelfLife: "24 months",
    storage: "Dry store",
    description: "Non-slip disinfectant floor cleaner rated for commercial kitchen wet areas.",
    tags: [],
    inStock: true,
  }),
];

export const products: Product[] = seeds.map((seed) => ({
  ...seed,
  image: `/products/${seed.id}.jpg`,
}));

export const productById = (id: string) => products.find((product) => product.id === id);

export const productsByCategory = (categorySlug: string) =>
  products.filter((product) => product.category === categorySlug);

export const bestsellers = () => products.filter((product) => product.tags.includes("Bestseller"));

export function searchProducts(query: string): Product[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  return products.filter((product) => {
    const haystack = [
      product.name,
      product.localName ?? "",
      product.category,
      product.subcategory,
      ...product.tags,
    ]
      .join(" ")
      .toLowerCase();
    return haystack.includes(q);
  });
}

/** Unit price after applying the best bulk slab the quantity qualifies for. */
export function effectivePrice(product: Product, qty: number): number {
  if (!product.bulkSlabs?.length) return product.price;
  const slab = [...product.bulkSlabs]
    .sort((a, b) => b.qty - a.qty)
    .find((candidate) => qty >= candidate.qty);
  return slab ? slab.price : product.price;
}
